config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :users
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/rides/:id/book', to: 'rides#book', as: 'book_ride'
  get '/rides/:id/cancel', to: 'rides#cancel', as: 'cancel_ride'

  get '/notifications/mark_as_read', to: 'notifications#mark_as_read', as: 'mark_as_read'

  resources :vehicles
  resources :rides
  resources :notifications
end

app/models/ride.rb
# frozen_string_literal: true

class Ride < ApplicationRecord
  include RideExceptions

  has_and_belongs_to_many :users, before_add: %i[ride_owner_cannot_book
                                                 cannot_book_full_ride]
  belongs_to :vehicle

  VALID_CAPACITY = /[1-9]/

  validates :origin, :destination, :departure_time, :capacity, :vehicle_id,
            presence: true

  validates :vehicle_id,
            uniqueness: { scope: :departure_time,
                          message: 'That ride already exists.' }

  validates :capacity,
            format: { with: VALID_CAPACITY }

  before_save :ride_capacity_not_more_than_vehicle,
              :departure_time_cannot_be_past,
              :invalid_capacity_update

  scope :available_rides, lambda {
    includes(:users)
      .where('departure_time > ?', Time.now)
      .order(created_at: :desc)
  }

  scope :filter_by_user, lambda { |user|
    joins(:users)
      .where(users: { id: user.id })
      .order(created_at: :desc)
  }

  scope :destination, lambda { |destination|
    where('lower(destination) like ?',
          "%#{destination.downcase}%")
  }

  def booked?(user)
    users.include? user
  end
end

app/controllers/rides_controller.rb
# frozen_string_literal: true

class RidesController < ApplicationController
  include ExceptionHandler
  include Notifications
  include FilterSearch

  before_action :require_login
  before_action :find_ride, only: %i[book cancel update destroy]

  def index
    @rides = Ride.available_rides
    filter_rides(params) if params[:filter] || params[:destination]
  end

  def create
    @ride = Ride.new(ride_params)
    if @ride.save
      ride_save_success
    else
      ride_save_error(@ride)
    end
  end

  def update
    if @ride.update(ride_params)
      @ride.users.each do |user|
        notify(user, update_message(@ride))
      end
      ride_save_success
    else
      ride_save_error(@ride)
    end
  end

  def book
    @ride.users << current_user
    notify(@ride.vehicle.user, book_message(@ride, current_user))
    flash[:success] = 'Ride booked!'
    redirect_to rides_path
  end

  def cancel
    @ride.users.delete(current_user)
    notify(@ride.vehicle.user, cancel_message(@ride, current_user))
    flash[:success] = 'Ride cancelled. What\'s up?'
    redirect_to rides_path
  end

  def destroy
    @ride.users.each do |user|
      notify(user, destroy_message(@ride))
    end
    @ride.destroy
    ride_save_success('Ride deleted. Now we have to walk?')
  end

  private

  def find_ride
    @ride = Ride.find(params[:id])
  end

  def ride_save_success(message = nil)
    flash[:success] = message || 'Ride saved!'
    redirect_to user_path(current_user)
  end

  def ride_save_error(ride)
    ride.errors.each do |_attr, message|
      flash[:danger] = message
    end
    redirect_to user_path(current_user)
  end

  def ride_params
    params.require(:ride).permit(:destination, :origin, :capacity,
                                 :departure_time, :vehicle_id)
  end

  def search_params(params)
    params.slice(:destination)
  end
end

app/views/rides/partials/_all_rides.html.erb
<% if @rides.empty? %>
  <p style="text-align: center; font-family: 'Gloria Hallelujah'; color: rgba(0, 0, 0, .6);">
    No rides yet. Come back later :-)
  </p>
<% else %>
  <% @rides.each do |ride| %>
    <%= render partial: "rides/partials/ride", locals: {user: current_user, ride: ride} %>
  <% end %>
<% end %>

app/views/rides/partials/_confirm_delete.html.erb
<div id="delete-ride-modal" class="modal">
  <div class="modal-content">
    <span class="close" data-dismiss="modal">&times;</span>
    <div class="modal-header">
      <p class="modal-heading">Are you sure?</p>
      <div class="modal-underline" />
    </div>
    <%= form_for :ride, method: :delete do |f| %>
      <div class="submit-button">
        <%= f.submit "Delete", class: "submit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rides/partials/_notifications.html.erb
<p class="notifications-tile">No Notifications yet. ;-)</p>

app/views/rides/partials/_ride.html.erb
<div class="tile-container-rides">
  <span><i class="fa fa-check"></i></span>
  <%= form_for :ride, url: ride_path(ride.id), html: {class: "tile"}, method: :patch do |f| %>
    <div class="tile-title">
      <div class="route">
        <div class="from-to">
          <%= image_tag "from.svg", title: "origin" %>
          <%= f.text_field :origin, required: true, value: ride.origin %>
        </div>
        <div>to</div>
        <div class="from-to">
          <%= image_tag "to.svg", title: "destination" %>
          <%= f.text_field :destination, required: true, value: ride.destination %>
        </div>
      </div>
      <%= f.datetime_local_field :departure_time, class: "time", required: true,
        value: ride.departure_time.strftime("%Y-%m-%dT%H:%M")
      %>
    </div>
    <div class="tile-content">
      <div class="ride-vehicle">
        <%= image_tag "vehicle.svg" %>
        <%= f.collection_select :vehicle_id, current_page?(rides_path) ? [ride.vehicle] : user.vehicles, :id, :license_plate,
          {selected: ride.vehicle.id},
          {class: "license-plate"}
        %>
      </div>
      <div class="seating-capacity">
        <%= image_tag "seats.svg" %>
        <%= f.text_field :capacity, required: true,
        class: "seats-left",
        pattern: '^[0-9]$',
        value: ride.capacity,
        title: "Capacity must be a number, e.g. 5"
        %>
        <%= f.label :seats %>
      </div>
      <div class="seating-capacity">
        <%= image_tag "capacity.svg" %>
        <div class="seats-left"><%=ride.users.count%></div>
        <div class="seats-left"><%=ride.users.count == 1 ? 'Rider' : 'Riders'%></div>
        <% passengers = ride.users.map(&:email) %>
        <% if passengers.any? %>
          <ul class="tooltip-text">
            <% passengers.each do |passenger| %>
              <li><%= passenger.split('@')[0] %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <div class="ride-color">
        <%= image_tag "palette.svg" %>
        <div class="ride-details"><%=ride.vehicle.color%> <%=ride.vehicle.make%> <%=ride.vehicle.model%></div>
      </div>
      <div class="ride-owner">
        <% if current_page?(rides_path) %>
          <div>by:</div>
          <% if ride.vehicle.user != user %>
            <div class="owner"><%=ride.vehicle.user.email.split('@')[0]%></div>
          <% else %>
            <div class="owner">you</div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="ride-footer">
      <div class="booked-btn update-btn" style="visibility: <%=ride.booked?(user) ? 'visible' : 'hidden' %>;">
        <i class="fa fa-check-square"></i>
        <div class="booked">You've booked this ride</div>
      </div>
      <div class="tile-update">
        <div class="edit-btn update-btn">
          <i class="fa fa-pencil"></i>
          <div class="edit edit-ride">Edit</div>
        </div>
        <div class="update-btn">
          <i class="fa fa-save"></i>
          <%= f.submit "Save", class: "save" %>
        </div>
        <% if ride.vehicle.user != user %>
          <div class="book-btn update-btn" style="display: <%=ride.booked?(user) ? 'none' : 'flex' %>;">
            <i class="fa fa-car"></i>
            <div class="edit-ride"><%= link_to "Book", book_ride_path(ride.id) %></div>
          </div>
        <% end %>
        <div class="delete-btn update-btn">
          <i class="fa fa-trash"></i>
          <div class="delete-ride"><%= link_to 'Delete', "#", data: {toggle: "modal", target: "#delete-ride-modal", href: ride_path(ride.id)} %></div>
        </div>
        <div class="cancel-btn update-btn" style="display: <%=ride.booked?(user) ? 'flex' : 'none' %>;">
          <i class="fa fa-ban"></i>
          <div class="delete-ride"><%= link_to "Cancel", cancel_ride_path(ride.id) %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/rides/partials/_ride_form.html.erb
<div id="ride-modal" class="modal">
  <div class="modal-content">
    <span class="close" data-dismiss="modal">&times;</span>
    <div class="modal-header">
      <p class="modal-heading">Add a Ride</p>
      <div class="modal-underline" />
    </div>
    <%= form_for :ride, url: rides_path do |f| %>
      <%= f.text_field :origin, required: true, placeholder: "Where from e.g. Andela Kenya" %>
      <%= f.text_field :destination, required: true, placeholder: "Where to e.g. Westlands" %>
      <%= f.datetime_local_field :departure_time, required: true,
        value: Time.now.localtime.strftime("%Y-%m-%dT%H:%M")
      %>
      <%= f.text_field :capacity, required: true,
      pattern: '^[0-9]$',
      title: "Capacity must be a number, e.g. 5",
      placeholder: "Capacity e.g. 5" %>
      <%= f.collection_select :vehicle_id, current_user.vehicles, :id, :license_plate,
        {prompt: "Select a Car"},
        {required: true}
      %>
      <div class="submit-button">
        <%= f.submit "Add", class: "submit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rides/partials/_rides_filter.html.erb
<span class="profile-setting vehicles">AVAILABLE RIDES</span>
<button class="filter-button vehicles">
  <span>Filter by </span><i class="fa fa-caret-down"></i>
  <div class="filter-dropdown">
    <%= link_to "Earliest added", rides_path(filter: 'asc'), remote: true, class: "filter-item date-added" %>
    <%= link_to "Rides I've booked", rides_path(filter: 'mine'), remote: true, class: "filter-item booked-rides" %>
  </div>
</button>