config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :users
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/rides/:id/book', to: 'rides#book', as: 'book_ride'
  get '/rides/:id/cancel', to: 'rides#cancel', as: 'cancel_ride'

  get '/notifications/mark_as_read', to: 'notifications#mark_as_read', as: 'mark_as_read'

  resources :vehicles
  resources :rides
  resources :notifications
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  has_many :rides, dependent: :destroy
  belongs_to :user

  VALID_PLATE = /[A-Z]{3} [0-9]{3}[A-Z]{1}/
  VALID_CAPACITY = /[1-9]/

  validates :make, :model, :license_plate, :capacity, :color,
            presence: true

  validates :license_plate,
            uniqueness: { message: 'That vehicle already exists.' },
            format: { with: VALID_PLATE }

  validates :capacity,
            format: { with: VALID_CAPACITY }
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  before_action :require_login
  before_action :find_vehicle, only: %i[update destroy]

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      vehicle_save_success
    else
      vehicle_save_error(@vehicle)
    end
  end

  def update
    if @vehicle.update(vehicle_params)
      vehicle_save_success
    else
      vehicle_save_error(@vehicle)
    end
  end

  def destroy
    if @vehicle.destroy
      vehicle_save_success('Shame. It was a nice car.')
    else
      vehicle_save_error(@vehicle)
    end
  end

  private

  def find_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_save_success(message = nil)
    flash[:success] = message || 'Vehicle saved!'
    redirect_to user_path(current_user.id)
  end

  def vehicle_save_error(vehicle)
    vehicle.errors.each do |_attr, message|
      flash[:danger] = message
    end
    redirect_to user_path(current_user.id)
  end

  def vehicle_params
    params.require(:vehicle).permit(:make, :model, :license_plate,
                                    :capacity, :color)
          .merge(user_id: current_user.id)
  end
end

app/views/vehicles/partials/_confirm_delete.html.erb
<div id="delete-vehicle-modal" class="modal">
  <div class="modal-content">
    <span class="close" data-dismiss="modal">&times;</span>
    <div class="modal-header">
      <p class="modal-heading">Are you sure?</p>
      <div class="modal-underline" />
    </div>
    <%= form_for :vehicle, method: :delete do |f| %>
      <div class="submit-button">
        <%= f.submit "Delete", class: "submit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/vehicles/partials/_vehicle_form.html.erb
<div id="vehicle-modal" class="modal">
  <div class="modal-content">
    <span class="close" data-dismiss="modal">&times;</span>
    <div class="modal-header">
      <p class="modal-heading">Add a Vehicle</p>
      <div class="modal-underline" />
    </div>
    <%= form_for :vehicle, url: vehicles_path do |f| %>
      <%= f.text_field :make, required: true, placeholder: "Make e.g. Toyota" %>
      <%= f.text_field :model, required: true, placeholder: "Model e.g. Corolla" %>
      <%= f.text_field :license_plate, required: true,
      pattern: '^[A-Z]{3} [0-9]{3}[A-Z]{1}$',
      placeholder: "License plate e.g. KCR 232C",
      title: "License Plate must be in this format: KCR 232C"
      %>
      <%= f.text_field :capacity, required: true,
      pattern: '^[0-9]$',
      title: "Capacity must be a number, e.g. 5",
      placeholder: "Capacity e.g. 5" %>
      <%= f.text_field :color, required: true, placeholder: "Color e.g. White" %>
      <div class="submit-button">
        <%= f.submit "Add", class: "submit" %>
      </div>
    <% end %>
  </div>
</div>