config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :users
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/rides/:id/book', to: 'rides#book', as: 'book_ride'
  get '/rides/:id/cancel', to: 'rides#cancel', as: 'cancel_ride'

  get '/notifications/mark_as_read', to: 'notifications#mark_as_read', as: 'mark_as_read'

  resources :vehicles
  resources :rides
  resources :notifications
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :vehicles, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_and_belongs_to_many :rides

  has_secure_password

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  VALID_PASSWORD = /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}/
  VALID_PHONE_NUMBER = /\A07[0-9]{8}\z/
  VALID_SLACK_HANDLE = /[@][a-z0-9][a-z0-9._-]*/

  validates :email,
            presence: true,
            uniqueness: { message: 'User already exists.' \
            ' Please Log In.' },
            format: { with: VALID_EMAIL }

  validates :password,
            presence: true,
            allow_nil: true,
            confirmation: true,
            format: { with: VALID_PASSWORD }

  validates :phone_number,
            format: { with: VALID_PHONE_NUMBER },
            allow_nil: true

  validates :slack_handle,
            format: { with: VALID_SLACK_HANDLE },
            allow_nil: true
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_login, only: %i[edit show]
  before_action :set_user, only: %i[show update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      user_save_success
    else
      user_save_error(@user, login_path)
    end
  end

  def show
    restrict_access unless @user == current_user
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Settings updated!'
      redirect_to user_path(current_user.id)
    else
      user_save_error(@user, user_path(current_user.id))
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_save_success
    session[:user] = @user.id
    redirect_to user_path(@user.id)
  end

  def user_save_error(user, path)
    user.errors.each do |_attr, message|
      flash[:danger] = message
    end
    redirect_to path
  end

  def restrict_access
    flash[:danger] = "You can't view that page"
    redirect_to rides_path
  end

  def user_params
    params.require(:user).permit(:email, :password, :confirm, :phone_number,
                                 :slack_handle, :phone_on, :slack_on)
  end
end

app/views/users/partials/_register_form.html.erb
<%= form_for :user, url: register_path do |f| %>
<div class="email">
  <i class="fa fa-user icon"></i>
  <%= f.email_field :email, required: true, placeholder: "you@example.com" %>
</div>
<div class="password">
  <i class="fa fa-key icon"></i>
  <%= f.password_field :password, required: true,
  pattern: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}',
  placeholder: "....",
  title: "Password must contain at least 6 characters, including UPPER/lowercase and numbers",
  onchange: "form.user_password_confirmation.pattern = RegExp.escape(this.value);"
  %>
</div>
<div class="confirm-password">
  <i class="fa fa-key icon"></i>
  <%= f.password_field :password_confirmation, required: true, placeholder: "....",
  title: "Please enter the same password as above"
  %>
</div>
<div class="remember">
  <%= check_box_tag :remember_me %>
  <p>Remember Me</p>
</div>
<%= f.submit "Register", class: "register-button" %>
<p class="toggle-login">
  Already have an account?
  <%= link_to 'Login', login_path, class: "to-login" %>
</p>
<% end %>

app/views/users/partials/_user_notifications.html.erb
<div class="tile-container notifications-tile">
  <span><i class="fa fa-check"></i></span>
  <%= form_for :user, url: user_path(user.id), html: {class: "tile"}, method: :patch do |f| %>
    <div class="tile-title">
      <div class="contact">
        <%= image_tag "contact.svg" %>
        <div class="contact-heading">CONTACT DETAILS</div>
      </div>
    </div>
    <div class="tile-content phone-number">
      <div class="phone">
        <%= image_tag "phone.svg" %>
        <%= f.text_field :phone_number,
          pattern: '^07[0-9]{8}$',
          value: user.phone_number,
          title: "Please enter a valid Kenyan phone number"
        %>
      </div>
      <div class="update-buttons">
        <div class="update-btn">
          <i class="fa fa-pencil"></i>
          <div class="edit">Edit</div>
        </div>
        <div class="update-btn">
          <i class="fa fa-save"></i>
          <%= f.submit "Save", class: "save" %>
        </div>
      </div>
    </div>
    <div class="tile-footer slack-handle">
      <div class="slack">
        <%= image_tag "slack.svg" %>
        <%= f.text_field :slack_handle,
          pattern: '^[@][a-z0-9][a-z0-9._-]*$',
          value: user.slack_handle,
          title: "Please start your slack handle with @"
        %>
      </div>
      <div class="update-buttons">
        <div class="update-btn">
          <i class="fa fa-pencil"></i>
          <div class="edit">Edit</div>
        </div>
        <div class="update-btn">
          <i class="fa fa-save"></i>
          <%= f.submit "Save", class: "save" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="tile-container notifications-tile">
  <span><i class="fa fa-check"></i></span>
  <%= form_for :user, url: user_path(user.id), html: {class: "tile"}, method: :patch do |f| %>
    <div class="tile-title">
      <div class="contact">
        <%= image_tag "settings.svg" %>
        <div class="contact-heading">PREFERENCES</div>
      </div>
    </div>
    <div class="tile-content">
      <div class="phone">
        <%= image_tag "phone.svg" %>
        <label class="switch">
          <%= f.check_box :phone_on, checked: user.phone_on, onchange: 'this.form.submit();' %>
          <div class="slider round"></div>
        </label>
      </div>
    </div>
    <div class="tile-footer">
      <div class="slack">
        <%= image_tag "slack.svg" %>
        <label class="switch">
          <%= f.check_box :slack_on, checked: user.slack_on, onchange: 'this.form.submit();' %>
          <div class="slider round"></div>
        </label>
      </div>
    </div>
  <% end %>
</div>

app/views/users/partials/_user_rides.html.erb
<div class="tiles-rides user-rides" style="top: 0; left: 0;">
  <% rides = current_user.vehicles.map(&:rides).flatten %>
  <% if rides.empty? %>
    <p style="text-align: center; font-family: 'Gloria Hallelujah'; color: rgba(0, 0, 0, .6);">
      You have no rides yet. Add one below :-)
    </p>
  <% else %>
    <% current_user.vehicles.each do |vehicle| %>
      <% vehicle.rides.each do |ride| %>
        <%= render partial: "rides/partials/ride", locals: {user: current_user, ride: ride} %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/partials/_user_vehicle.html.erb
<div class="tile-container-settings vehicle-tile">
  <span><i class="fa fa-check"></i></span>
  <%= form_for :vehicle, url: vehicle_path(vehicle.id), html: {class: "tile"}, method: :patch do |f| %>
    <div class="tile-title">
      <div class="vehicle">
        <%= image_tag "vehicle.svg" %>
        <div class="make-model">
          <%= f.text_field :make, required: true, value: vehicle.make %>
          <%= f.text_field :model, required: true, value: vehicle.model %>
        </div>
      </div>
      <div class="rides-history">Rides Offered: <%= vehicle.rides.count %></div>
    </div>
    <div class="tile-content">
      <div class="license">
        <%= image_tag "license-plate.svg" %>
        <div class="plate">
          <%= f.text_field :license_plate, required: true,
          pattern: '^[A-Z]{3} [0-9]{3}[A-Z]{1}$',
          value: vehicle.license_plate,
          title: "License Plate must be in this format: KCR 232C"
          %>
        </div>
      </div>
      <div class="capacity">
        <%= image_tag "capacity.svg" %>
        <div class="seating">
          <%= f.text_field :capacity, required: true,
          pattern: '^[0-9]$',
          value: vehicle.capacity,
          title: "Capacity must be a number, e.g. 5"
          %>
        </div>
      </div>
      <div class="color">
        <%= image_tag "palette.svg" %>
        <div class="hue">
          <%= f.text_field :color, required: true, value: vehicle.color %>
        </div>
      </div>
    </div>
    <div class="tile-update">
      <div class="update-btn">
        <i class="fa fa-pencil"></i>
        <div class="edit">Edit</div>
      </div>
      <div class="update-btn">
        <i class="fa fa-save"></i>
        <%= f.submit "Save", class: "save" %>
      </div>
      <div class="update-btn">
        <i class="fa fa-trash"></i>
        <div class="delete"><%= link_to 'Delete', "#", data: {toggle: "modal", target: "#delete-vehicle-modal", href: vehicle_path(vehicle.id)} %></div>
      </div>
    </div>
  <% end %>
</div>