config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :users
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/rides/:id/book', to: 'rides#book', as: 'book_ride'
  get '/rides/:id/cancel', to: 'rides#cancel', as: 'cancel_ride'

  get '/notifications/mark_as_read', to: 'notifications#mark_as_read', as: 'mark_as_read'

  resources :vehicles
  resources :rides
  resources :notifications
end

app/views/layouts/partials/_flash.html.erb
<%= stylesheet_link_tag "flash" %>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" style="margin: 0; display: none;">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/partials/_notification_dropdown.html.erb
<div class="notifications-icon">
  <%= image_tag "bell_icon.svg" %>
  <span class="badge"><%= current_user.notifications.where(read: false).count %></span>
  <div class="notifications-dropdown">
    <%= link_to "Mark all as read", mark_as_read_path, remote: true, class: "mark-read" %>
    <% if current_user.notifications.where(read: false).empty? %>
      <div class="notification" style="text-align: center; font-family: 'Gloria Hallelujah'; color: rgba(0, 0, 0, .6);">
        Nothing's happened yet! :-)
      </div>
    <% else %>
      <% current_user.notifications.where(read: false).each do |notification| %>
        <div class="notification"><%= notification.message %></div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/partials/_side_nav.html.erb
<nav class="left-nav">
  <div class="logo">
    <%= image_tag "car-profile.svg" %>
    <p>Rydr</p>
  </div>
  <div class="nav-title">
    <% if current_page?(user_path(current_user.id)) %>
      <i class="fa fa-cogs"></i>
      <span> Settings</span>
    <% elsif current_page?(rides_path) %>
      <i class="fa fa-car"></i>
      <span> Available Rides</span>
    <% end %>
  </div>
  <div class="line-break"></div>
  <%= link_to rides_path, class: "left-nav-link rides-nav" do %>
      <i class="fa fa-car"></i><span>AVAILABLE RIDES</span>
  <% end %>
  <%= link_to user_path(current_user.id), class: "left-nav-link settings-nav" do %>
      <i class="fa fa-cogs"></i><span>SETTINGS</span>
  <% end %>
  <div class="line-break"></div>
</nav>

app/views/layouts/partials/_top_nav.html.erb
<nav class="top-nav">
  <% if current_page?(rides_path) %>
    <%= form_tag rides_path, method: :get, remote: true, class: "search-form" do %>
      <div class="search">
        <%= search_field_tag :destination, params[:destination], placeholder: 'Where are you going?' %>
      </div>
      <%= submit_tag "Search", name: nil, class: "search-button", style: "display: none;" %>
    <% end %>
  <% end %>
  <div class="right-top-nav">
    <div class="notifications-top-nav">
      <%= render partial: "layouts/partials/notification_dropdown" %>
    </div>
    <div class="current-user">
      <%= image_tag "user.svg" %>
      <span><%= current_user.email %></span>
    </div>
    <div class="dropdown-button">
      <%= image_tag "menu.svg" %>
      <div class="dropdown-content">
        <%= link_to "Logout", logout_path %>
      </div>
    </div>
  </div>
</nav>